spring:
  application:
    name: eureka
  security:
    user:
      name: ${EUREKA_USERNAME:eureka}
      password: ${EUREKA_PASSWORD:password}

server:
  port: 8761
  error:
    include-message: always

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false

